Add QWeb Library
MarketSquare/awesome-robotframework pull request #25
Opened 2021-11-08 01:33 UTC by kalyncoose

2021-11-08 16:59 UTC, fkromer requested changes
As far as I know the awesome linter does allow a single hyperlink per line only. Can you remove the github and keywords hyperlinks?

2021-11-10 01:03 UTC, kalyncoose commented
I did notice that Line 41 (two lines above mine) has two hyperlinks in one line. Is it still an issue?
```
 - [Swing Library](https://github.com/robotframework/SwingLibrary) ([keyword documentation](https://robotframework.org/SwingLibrary/SwingLibrary-1.9.7.html)) Library for testing Java applications with Swing GUI.
```

2021-11-10 09:22 UTC, fkromer commented
Please change your PR to include only obe hyperlink. I‘ll fix the Swig lib entry later.

2025-03-07 20:55 UTC, MobyNL commented
Current change includes non existing link. Needs fix before merge

2025-03-07 21:15 UTC, MobyNL commented
One of the links was not working anymore, and since I couldn't change this PR, I added it through another branch. It is now included in the list.

2025-03-07 21:15 UTC, closed without merging